### ISSUE TITLE
Drop rustc-serialize support

### ISSUE THREAD

**Issue by dtolnay** [abonander/anterofit#2]
According to [Rust release milestone predictions](https://internals.rust-lang.org/t/rust-release-milestone-predictions/4591?u=dtolnay), rustc-serialize is scheduled to be deprecated in next month's beta release of Rust.

**Comment by abonander** [comment]
I'd like to keep support for legacy reasons, but I can make Serde the default.

**Comment by dtolnay** [comment]
I guess the opposite perspective would be that codebases that are using an outdated serialization library will always be able to use an outdated `anterofit` as well. They can just stick to the latest version that provides rustc-serialize support. In the meantime, new users will not need to wade past irrelevant code and irrelevant cargo cfgs when reviewing the code or documentation of this crate.

**Comment by abonander** [comment]
The effect on compilation time is negligible and it allows fitting Anterofit into codebases already using `rustc-serialize`.

**Comment by abonander** [comment]
Serde is now the default.
