### ISSUE TITLE
Serde compile times

### ISSUE THREAD

**Issue by dtolnay** [abonander/anterofit#3]
In the readme under "Slower compilation" one of the things you wrote is:

> Procedural macros currently have to reparse the token stream instead of reusing compiler datastructures

Is this an actual thing that you have measured? Or is it just a guess?

My experience has always been that macro expansion (including parsing and code generation) is a negligible part of compile time compared to time spent in LLVM.

**Comment by abonander** [comment]
I wrote that while custom derive was still unstable and Serde was still based on Syntex, which does take significant time to compile. It's basically a non-issue now with custom derive and the compiler team is working on improving the `TokenStream` API so it won't have to deal entirely in strings like it does now. In microbenchmarks it's probably slower, but you're right, most of the time in compilation is spent in trans anyway.

**Comment by abonander** [comment]
Removed the comparison.
