### ISSUE TITLE
Consider implementing OpenAPI (Swagger) specification

### ISSUE THREAD

**Issue by frol** [abonander/anterofit#4]
You already have annotations, which is great. Using the annotations you can build OpenAPI description of the API endpoints, which can be used to generate API clients in a number of programming languages.

OpenAPI: https://www.openapis.org
Swagger examples: http://swagger.io

**Comment by abonander** [comment]
Unless I'm fundamentally misunderstanding something, this seems like it can be implemented with a build script that generates `service!{}` declarations.

**Comment by frol** [comment]
I mean the other way around, allow to generate a swagger.json from the server code inspection, see this example written in Python: https://github.com/frol/flask-restplus-server-example

**Comment by abonander** [comment]
Sorry, this is a client framework. I've only just realized I may not have made that very clear.

**Comment by frol** [comment]
Ah... I felt like I miss something... :) Sorry for bothering you.
