### ISSUE TITLE
Complile problem with Hyper 0.10.5 using adapter.client(client) to set a proxy

### ISSUE THREAD

**Issue by aguindehi** [abonander/anterofit#5]
Hi!

I successfully used anterofit with Hyper 0.9. After upgrading to Hyper 0.10 I get the following error:

> 96 |             adapter = adapter.client(client)
>    |                                      ^^^^^^ expected struct anterofit::<unnamed>::Client, found struct hyper::Client
>    |
>    = note: expected type `anterofit::<unnamed>::Client`
>    = note:    found type `hyper::Client`

The code resulting in the above error tries to set a proxy host and port on the client and then adds it to the adapter's builder:

`
            let client = Client::with_http_proxy(proxy_host, proxy_port);
            adapter = adapter.client(client)
`

This fails with the above error since upgrading to Hyper 0.10. It worked fine with Hyper 0.9.
Do you have an idea what's going wrong there?

Keep up the great work!

Cheers!
Amir

**Comment by abonander** [comment]
Yeah, this is a typical error when you have mismatched dependencies. Anterofit requires Hyper 0.9 (actually it's strictly 0.9.12 but I think I can drop the patch version). I'll probably patch Anterofit and `multipart` to allow `hyper >= 0.9, < 0.11`.

**Comment by aguindehi** [comment]
Oh, I was not aware of the < Hyper 0.10 dependency! That explains it. ;)

**Comment by aguindehi** [comment]
I guess I should close this issue, as it will automatically get resolved when Hyper 0.10 gets supported.
