### ISSUE TITLE
Support Hyper 0.10

### ISSUE THREAD

**Issue by abonander** [abonander/anterofit#6]
I think this is as simple as doing `hyper = ">=0.9, < 0.11"` for Anterofit and multipart, but it probably needs testing.

**Comment by abonander** [comment]
Blocked on nickel-org/nickel.rs#395

**Comment by IslandUsurper** [comment]
nickel-org/nickel.rs#395 was apparently resolved by nickel-org/nickel.rs#401.

**Comment by abonander** [comment]
Well the issue was mostly eliminated by moving Nickel support out of mainline `multipart`, I just haven't had time to work on this project lately. I'm also waiting for both async Hyper and procedural macros beyond custom derive to stabilize. I believe with procedural attribute macros, I can support simpler and more elegant syntax without an exponential blowup of macro cases. 

I've thought about how I can make it work with custom derive but that would require turning service traits into structs, I think, where the service methods become inherent methods and the derived trait is like `FromAdapter` or something (though custom derive doesn't currently restrict the generated code to an impl of the named trait). 

It would work but the main issue is serializers and deserializers; since they can't be type-erased, the exact serializer/deserializer types either have to be hardcoded into service struct definitions or else each struct has to be generic over them (or the adapter type itself), and that means forcing generics on any function that takes service structs. I really do prefer the trait approach as it allows type erasure and passing services around as opaque types while still being generic over (de)serializer types, but it makes it more difficult to adapt them to custom-derive though I think I could make it work still.

**Comment by discosultan** [comment]
What's the status on this? I'm running into troubles during compilation because of the old version of Hyper still using an ssl library incompatible with OpenSSL 1.1.0 lib and includes.

**Comment by abonander** [comment]
@discosultan The latest version of Multipart supports Hyper 0.10, I'm not sure why this is still open.

**Comment by abonander** [comment]
Sorry, I was thinking about the wrong repo. I'll get something out later today.

**Comment by discosultan** [comment]
That'd be awesome, thanks @abonander!
